name: uni_ride
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.66.0
  permission_handler: ^11.0.1
  geolocator: ^13.0.1
  google_maps_flutter: ^2.5.3
  geocoding: ^3.0.0
  image_picker: ^1.0.7
  google_places_flutter: ^2.0.6
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  socket_io_client: ^3.0.2

  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/UniRide_App_Icon.png"

flutter:
  uses-material-design: true

  assets:
    - images/reserve.png