// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ep25WGkSkrW7knxwcUfpTyQQh5qwpKs',
    appId: '1:734069954022:web:54983802cd57ee51023227',
    messagingSenderId: '734069954022',
    projectId: 'uniride-7632e',
    authDomain: 'uniride-7632e.firebaseapp.com',
    storageBucket: 'uniride-7632e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjImNK5vlEjEMc4rGC1zPQ0cGlub2UfXA',
    appId: '1:734069954022:android:3e81769f3249c333023227',
    messagingSenderId: '734069954022',
    projectId: 'uniride-7632e',
    storageBucket: 'uniride-7632e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ5V70lhFWRLVp35B_Q5yNgDSVO7KBixU',
    appId: '1:734069954022:ios:d995e586df59565e023227',
    messagingSenderId: '734069954022',
    projectId: 'uniride-7632e',
    storageBucket: 'uniride-7632e.firebasestorage.app',
    iosBundleId: 'com.UnitedGroup.uniRide',
  );
}
